language: php

php:
    - 7.4
    - 8.0
    - 8.1
    - 8.2

matrix:
    include:
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - composer self-update
    - composer --version
    - if [ "$TRAVIS_PHP_VERSION" == "8.1" ]; then wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "8.1" ]; then php php-cs-fixer.phar --version; fi

install:
    - COMPOSER_ROOT_VERSION=dev-master COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-source $COMPOSER_FLAGS

script:
    - if [ "$TRAVIS_PHP_VERSION" == "8.1" ]; then php php-cs-fixer.phar fix --dry-run -v; fi
    - if [ "$TRAVIS_PHP_VERSION" != "8.1" ]; then bin/phpunit; fi
